# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: shared.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='shared.proto',
  package='shared',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0cshared.proto\x12\x06shared\x1a\x1egoogle/protobuf/wrappers.proto\">\n\nAppService\x12\x30\n\ncredential\x18\x01 \x01(\x0e\x32\x1c.shared.AppServiceCredential\"s\n\x12\x41ppServiceResponse\x12\x13\n\x0b\x65ncoded_key\x18\x01 \x01(\t\x12\x16\n\x0e\x65ncoded_secret\x18\x02 \x01(\t\x12\x30\n\ncredential\x18\x03 \x01(\x0e\x32\x1c.shared.AppServiceCredential\"=\n\x12\x41piVersionResponse\x12\x0f\n\x07version\x18\x01 \x01(\t\x12\x16\n\x0eshould_upgrade\x18\x02 \x01(\x08*8\n\x14\x41ppServiceCredential\x12\x0f\n\x0bgoogle_auth\x10\x00\x12\x0f\n\x0bgoogle_maps\x10\x01\x32\xbd\x01\n\rSharedService\x12]\n!get_api_latest_version_for_client\x12\x1c.google.protobuf.StringValue\x1a\x1a.shared.ApiVersionResponse\x12M\n\x1bget_app_service_credentials\x12\x12.shared.AppService\x1a\x1a.shared.AppServiceResponseb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_wrappers__pb2.DESCRIPTOR,])

_APPSERVICECREDENTIAL = _descriptor.EnumDescriptor(
  name='AppServiceCredential',
  full_name='shared.AppServiceCredential',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='google_auth', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='google_maps', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=300,
  serialized_end=356,
)
_sym_db.RegisterEnumDescriptor(_APPSERVICECREDENTIAL)

AppServiceCredential = enum_type_wrapper.EnumTypeWrapper(_APPSERVICECREDENTIAL)
google_auth = 0
google_maps = 1



_APPSERVICE = _descriptor.Descriptor(
  name='AppService',
  full_name='shared.AppService',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='credential', full_name='shared.AppService.credential', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=56,
  serialized_end=118,
)


_APPSERVICERESPONSE = _descriptor.Descriptor(
  name='AppServiceResponse',
  full_name='shared.AppServiceResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='encoded_key', full_name='shared.AppServiceResponse.encoded_key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='encoded_secret', full_name='shared.AppServiceResponse.encoded_secret', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='credential', full_name='shared.AppServiceResponse.credential', index=2,
      number=3, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=235,
)


_APIVERSIONRESPONSE = _descriptor.Descriptor(
  name='ApiVersionResponse',
  full_name='shared.ApiVersionResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='version', full_name='shared.ApiVersionResponse.version', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='should_upgrade', full_name='shared.ApiVersionResponse.should_upgrade', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=237,
  serialized_end=298,
)

_APPSERVICE.fields_by_name['credential'].enum_type = _APPSERVICECREDENTIAL
_APPSERVICERESPONSE.fields_by_name['credential'].enum_type = _APPSERVICECREDENTIAL
DESCRIPTOR.message_types_by_name['AppService'] = _APPSERVICE
DESCRIPTOR.message_types_by_name['AppServiceResponse'] = _APPSERVICERESPONSE
DESCRIPTOR.message_types_by_name['ApiVersionResponse'] = _APIVERSIONRESPONSE
DESCRIPTOR.enum_types_by_name['AppServiceCredential'] = _APPSERVICECREDENTIAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

AppService = _reflection.GeneratedProtocolMessageType('AppService', (_message.Message,), {
  'DESCRIPTOR' : _APPSERVICE,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:shared.AppService)
  })
_sym_db.RegisterMessage(AppService)

AppServiceResponse = _reflection.GeneratedProtocolMessageType('AppServiceResponse', (_message.Message,), {
  'DESCRIPTOR' : _APPSERVICERESPONSE,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:shared.AppServiceResponse)
  })
_sym_db.RegisterMessage(AppServiceResponse)

ApiVersionResponse = _reflection.GeneratedProtocolMessageType('ApiVersionResponse', (_message.Message,), {
  'DESCRIPTOR' : _APIVERSIONRESPONSE,
  '__module__' : 'shared_pb2'
  # @@protoc_insertion_point(class_scope:shared.ApiVersionResponse)
  })
_sym_db.RegisterMessage(ApiVersionResponse)



_SHAREDSERVICE = _descriptor.ServiceDescriptor(
  name='SharedService',
  full_name='shared.SharedService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=359,
  serialized_end=548,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_api_latest_version_for_client',
    full_name='shared.SharedService.get_api_latest_version_for_client',
    index=0,
    containing_service=None,
    input_type=google_dot_protobuf_dot_wrappers__pb2._STRINGVALUE,
    output_type=_APIVERSIONRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get_app_service_credentials',
    full_name='shared.SharedService.get_app_service_credentials',
    index=1,
    containing_service=None,
    input_type=_APPSERVICE,
    output_type=_APPSERVICERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SHAREDSERVICE)

DESCRIPTOR.services_by_name['SharedService'] = _SHAREDSERVICE

# @@protoc_insertion_point(module_scope)
