import './globals.css'
import {DM_Sans} from 'next/font/google'

const dmSans = DM_Sans({subsets: ["latin"], weight: "400"})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dmSans.className}>{children}</body>
    </html>
  )
}
