/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.41.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum AccountEnumType {
    #[serde(rename = "Trial")]
    Trial,
    #[serde(rename = "Full")]
    Full,

}

impl ToString for AccountEnumType {
    fn to_string(&self) -> String {
        match self {
            Self::Trial => String::from("Trial"),
            Self::Full => String::from("Full"),
        }
    }
}

impl Default for AccountEnumType {
    fn default() -> AccountEnumType {
        Self::Trial
    }
}




