/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.41.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConferenceEnumReasonConferenceEnded {
    #[serde(rename = "conference-ended-via-api")]
    ConferenceEndedViaApi,
    #[serde(rename = "participant-with-end-conference-on-exit-left")]
    ParticipantWithEndConferenceOnExitLeft,
    #[serde(rename = "participant-with-end-conference-on-exit-kicked")]
    ParticipantWithEndConferenceOnExitKicked,
    #[serde(rename = "last-participant-kicked")]
    LastParticipantKicked,
    #[serde(rename = "last-participant-left")]
    LastParticipantLeft,

}

impl ToString for ConferenceEnumReasonConferenceEnded {
    fn to_string(&self) -> String {
        match self {
            Self::ConferenceEndedViaApi => String::from("conference-ended-via-api"),
            Self::ParticipantWithEndConferenceOnExitLeft => String::from("participant-with-end-conference-on-exit-left"),
            Self::ParticipantWithEndConferenceOnExitKicked => String::from("participant-with-end-conference-on-exit-kicked"),
            Self::LastParticipantKicked => String::from("last-participant-kicked"),
            Self::LastParticipantLeft => String::from("last-participant-left"),
        }
    }
}

impl Default for ConferenceEnumReasonConferenceEnded {
    fn default() -> ConferenceEnumReasonConferenceEnded {
        Self::ConferenceEndedViaApi
    }
}




