/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.41.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum IncomingPhoneNumberTollFreeEnumAddressRequirement {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "any")]
    Any,
    #[serde(rename = "local")]
    Local,
    #[serde(rename = "foreign")]
    Foreign,

}

impl ToString for IncomingPhoneNumberTollFreeEnumAddressRequirement {
    fn to_string(&self) -> String {
        match self {
            Self::None => String::from("none"),
            Self::Any => String::from("any"),
            Self::Local => String::from("local"),
            Self::Foreign => String::from("foreign"),
        }
    }
}

impl Default for IncomingPhoneNumberTollFreeEnumAddressRequirement {
    fn default() -> IncomingPhoneNumberTollFreeEnumAddressRequirement {
        Self::None
    }
}




