/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.41.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum MessageFeedbackEnumOutcome {
    #[serde(rename = "confirmed")]
    Confirmed,
    #[serde(rename = "unconfirmed")]
    Unconfirmed,

}

impl ToString for MessageFeedbackEnumOutcome {
    fn to_string(&self) -> String {
        match self {
            Self::Confirmed => String::from("confirmed"),
            Self::Unconfirmed => String::from("unconfirmed"),
        }
    }
}

impl Default for MessageFeedbackEnumOutcome {
    fn default() -> MessageFeedbackEnumOutcome {
        Self::Confirmed
    }
}




