/*
 * Twilio - Api
 *
 * This is the public Twilio REST API.
 *
 * The version of the OpenAPI document: 1.41.0
 * Contact: support@twilio.com
 * Generated by: https://openapi-generator.tech
 */


/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum UsageRecordLastMonthEnumCategory {
    #[serde(rename = "a2p-registration-fees")]
    A2pRegistrationFees,
    #[serde(rename = "agent-conference")]
    AgentConference,
    #[serde(rename = "amazon-polly")]
    AmazonPolly,
    #[serde(rename = "answering-machine-detection")]
    AnsweringMachineDetection,
    #[serde(rename = "authy-authentications")]
    AuthyAuthentications,
    #[serde(rename = "authy-calls-outbound")]
    AuthyCallsOutbound,
    #[serde(rename = "authy-monthly-fees")]
    AuthyMonthlyFees,
    #[serde(rename = "authy-phone-intelligence")]
    AuthyPhoneIntelligence,
    #[serde(rename = "authy-phone-verifications")]
    AuthyPhoneVerifications,
    #[serde(rename = "authy-sms-outbound")]
    AuthySmsOutbound,
    #[serde(rename = "call-progess-events")]
    CallProgessEvents,
    #[serde(rename = "calleridlookups")]
    Calleridlookups,
    #[serde(rename = "calls")]
    Calls,
    #[serde(rename = "calls-client")]
    CallsClient,
    #[serde(rename = "calls-globalconference")]
    CallsGlobalconference,
    #[serde(rename = "calls-inbound")]
    CallsInbound,
    #[serde(rename = "calls-inbound-local")]
    CallsInboundLocal,
    #[serde(rename = "calls-inbound-mobile")]
    CallsInboundMobile,
    #[serde(rename = "calls-inbound-tollfree")]
    CallsInboundTollfree,
    #[serde(rename = "calls-outbound")]
    CallsOutbound,
    #[serde(rename = "calls-pay-verb-transactions")]
    CallsPayVerbTransactions,
    #[serde(rename = "calls-recordings")]
    CallsRecordings,
    #[serde(rename = "calls-sip")]
    CallsSip,
    #[serde(rename = "calls-sip-inbound")]
    CallsSipInbound,
    #[serde(rename = "calls-sip-outbound")]
    CallsSipOutbound,
    #[serde(rename = "calls-transfers")]
    CallsTransfers,
    #[serde(rename = "carrier-lookups")]
    CarrierLookups,
    #[serde(rename = "conversations")]
    Conversations,
    #[serde(rename = "conversations-api-requests")]
    ConversationsApiRequests,
    #[serde(rename = "conversations-conversation-events")]
    ConversationsConversationEvents,
    #[serde(rename = "conversations-endpoint-connectivity")]
    ConversationsEndpointConnectivity,
    #[serde(rename = "conversations-events")]
    ConversationsEvents,
    #[serde(rename = "conversations-participant-events")]
    ConversationsParticipantEvents,
    #[serde(rename = "conversations-participants")]
    ConversationsParticipants,
    #[serde(rename = "cps")]
    Cps,
    #[serde(rename = "flex-usage")]
    FlexUsage,
    #[serde(rename = "fraud-lookups")]
    FraudLookups,
    #[serde(rename = "group-rooms")]
    GroupRooms,
    #[serde(rename = "group-rooms-data-track")]
    GroupRoomsDataTrack,
    #[serde(rename = "group-rooms-encrypted-media-recorded")]
    GroupRoomsEncryptedMediaRecorded,
    #[serde(rename = "group-rooms-media-downloaded")]
    GroupRoomsMediaDownloaded,
    #[serde(rename = "group-rooms-media-recorded")]
    GroupRoomsMediaRecorded,
    #[serde(rename = "group-rooms-media-routed")]
    GroupRoomsMediaRouted,
    #[serde(rename = "group-rooms-media-stored")]
    GroupRoomsMediaStored,
    #[serde(rename = "group-rooms-participant-minutes")]
    GroupRoomsParticipantMinutes,
    #[serde(rename = "group-rooms-recorded-minutes")]
    GroupRoomsRecordedMinutes,
    #[serde(rename = "imp-v1-usage")]
    ImpV1Usage,
    #[serde(rename = "lookups")]
    Lookups,
    #[serde(rename = "marketplace")]
    Marketplace,
    #[serde(rename = "marketplace-algorithmia-named-entity-recognition")]
    MarketplaceAlgorithmiaNamedEntityRecognition,
    #[serde(rename = "marketplace-cadence-transcription")]
    MarketplaceCadenceTranscription,
    #[serde(rename = "marketplace-cadence-translation")]
    MarketplaceCadenceTranslation,
    #[serde(rename = "marketplace-capio-speech-to-text")]
    MarketplaceCapioSpeechToText,
    #[serde(rename = "marketplace-convriza-ababa")]
    MarketplaceConvrizaAbaba,
    #[serde(rename = "marketplace-deepgram-phrase-detector")]
    MarketplaceDeepgramPhraseDetector,
    #[serde(rename = "marketplace-digital-segment-business-info")]
    MarketplaceDigitalSegmentBusinessInfo,
    #[serde(rename = "marketplace-facebook-offline-conversions")]
    MarketplaceFacebookOfflineConversions,
    #[serde(rename = "marketplace-google-speech-to-text")]
    MarketplaceGoogleSpeechToText,
    #[serde(rename = "marketplace-ibm-watson-message-insights")]
    MarketplaceIbmWatsonMessageInsights,
    #[serde(rename = "marketplace-ibm-watson-message-sentiment")]
    MarketplaceIbmWatsonMessageSentiment,
    #[serde(rename = "marketplace-ibm-watson-recording-analysis")]
    MarketplaceIbmWatsonRecordingAnalysis,
    #[serde(rename = "marketplace-ibm-watson-tone-analyzer")]
    MarketplaceIbmWatsonToneAnalyzer,
    #[serde(rename = "marketplace-icehook-systems-scout")]
    MarketplaceIcehookSystemsScout,
    #[serde(rename = "marketplace-infogroup-dataaxle-bizinfo")]
    MarketplaceInfogroupDataaxleBizinfo,
    #[serde(rename = "marketplace-keen-io-contact-center-analytics")]
    MarketplaceKeenIoContactCenterAnalytics,
    #[serde(rename = "marketplace-marchex-cleancall")]
    MarketplaceMarchexCleancall,
    #[serde(rename = "marketplace-marchex-sentiment-analysis-for-sms")]
    MarketplaceMarchexSentimentAnalysisForSms,
    #[serde(rename = "marketplace-marketplace-nextcaller-social-id")]
    MarketplaceMarketplaceNextcallerSocialId,
    #[serde(rename = "marketplace-mobile-commons-opt-out-classifier")]
    MarketplaceMobileCommonsOptOutClassifier,
    #[serde(rename = "marketplace-nexiwave-voicemail-to-text")]
    MarketplaceNexiwaveVoicemailToText,
    #[serde(rename = "marketplace-nextcaller-advanced-caller-identification")]
    MarketplaceNextcallerAdvancedCallerIdentification,
    #[serde(rename = "marketplace-nomorobo-spam-score")]
    MarketplaceNomoroboSpamScore,
    #[serde(rename = "marketplace-payfone-tcpa-compliance")]
    MarketplacePayfoneTcpaCompliance,
    #[serde(rename = "marketplace-remeeting-automatic-speech-recognition")]
    MarketplaceRemeetingAutomaticSpeechRecognition,
    #[serde(rename = "marketplace-tcpa-defense-solutions-blacklist-feed")]
    MarketplaceTcpaDefenseSolutionsBlacklistFeed,
    #[serde(rename = "marketplace-telo-opencnam")]
    MarketplaceTeloOpencnam,
    #[serde(rename = "marketplace-truecnam-true-spam")]
    MarketplaceTruecnamTrueSpam,
    #[serde(rename = "marketplace-twilio-caller-name-lookup-us")]
    MarketplaceTwilioCallerNameLookupUs,
    #[serde(rename = "marketplace-twilio-carrier-information-lookup")]
    MarketplaceTwilioCarrierInformationLookup,
    #[serde(rename = "marketplace-voicebase-pci")]
    MarketplaceVoicebasePci,
    #[serde(rename = "marketplace-voicebase-transcription")]
    MarketplaceVoicebaseTranscription,
    #[serde(rename = "marketplace-voicebase-transcription-custom-vocabulary")]
    MarketplaceVoicebaseTranscriptionCustomVocabulary,
    #[serde(rename = "marketplace-whitepages-pro-caller-identification")]
    MarketplaceWhitepagesProCallerIdentification,
    #[serde(rename = "marketplace-whitepages-pro-phone-intelligence")]
    MarketplaceWhitepagesProPhoneIntelligence,
    #[serde(rename = "marketplace-whitepages-pro-phone-reputation")]
    MarketplaceWhitepagesProPhoneReputation,
    #[serde(rename = "marketplace-wolfarm-spoken-results")]
    MarketplaceWolfarmSpokenResults,
    #[serde(rename = "marketplace-wolfram-short-answer")]
    MarketplaceWolframShortAnswer,
    #[serde(rename = "marketplace-ytica-contact-center-reporting-analytics")]
    MarketplaceYticaContactCenterReportingAnalytics,
    #[serde(rename = "mediastorage")]
    Mediastorage,
    #[serde(rename = "mms")]
    Mms,
    #[serde(rename = "mms-inbound")]
    MmsInbound,
    #[serde(rename = "mms-inbound-longcode")]
    MmsInboundLongcode,
    #[serde(rename = "mms-inbound-shortcode")]
    MmsInboundShortcode,
    #[serde(rename = "mms-messages-carrierfees")]
    MmsMessagesCarrierfees,
    #[serde(rename = "mms-outbound")]
    MmsOutbound,
    #[serde(rename = "mms-outbound-longcode")]
    MmsOutboundLongcode,
    #[serde(rename = "mms-outbound-shortcode")]
    MmsOutboundShortcode,
    #[serde(rename = "monitor-reads")]
    MonitorReads,
    #[serde(rename = "monitor-storage")]
    MonitorStorage,
    #[serde(rename = "monitor-writes")]
    MonitorWrites,
    #[serde(rename = "notify")]
    Notify,
    #[serde(rename = "notify-actions-attempts")]
    NotifyActionsAttempts,
    #[serde(rename = "notify-channels")]
    NotifyChannels,
    #[serde(rename = "number-format-lookups")]
    NumberFormatLookups,
    #[serde(rename = "pchat")]
    Pchat,
    #[serde(rename = "pchat-users")]
    PchatUsers,
    #[serde(rename = "peer-to-peer-rooms-participant-minutes")]
    PeerToPeerRoomsParticipantMinutes,
    #[serde(rename = "pfax")]
    Pfax,
    #[serde(rename = "pfax-minutes")]
    PfaxMinutes,
    #[serde(rename = "pfax-minutes-inbound")]
    PfaxMinutesInbound,
    #[serde(rename = "pfax-minutes-outbound")]
    PfaxMinutesOutbound,
    #[serde(rename = "pfax-pages")]
    PfaxPages,
    #[serde(rename = "phonenumbers")]
    Phonenumbers,
    #[serde(rename = "phonenumbers-cps")]
    PhonenumbersCps,
    #[serde(rename = "phonenumbers-emergency")]
    PhonenumbersEmergency,
    #[serde(rename = "phonenumbers-local")]
    PhonenumbersLocal,
    #[serde(rename = "phonenumbers-mobile")]
    PhonenumbersMobile,
    #[serde(rename = "phonenumbers-setups")]
    PhonenumbersSetups,
    #[serde(rename = "phonenumbers-tollfree")]
    PhonenumbersTollfree,
    #[serde(rename = "premiumsupport")]
    Premiumsupport,
    #[serde(rename = "proxy")]
    Proxy,
    #[serde(rename = "proxy-active-sessions")]
    ProxyActiveSessions,
    #[serde(rename = "pstnconnectivity")]
    Pstnconnectivity,
    #[serde(rename = "pv")]
    Pv,
    #[serde(rename = "pv-composition-media-downloaded")]
    PvCompositionMediaDownloaded,
    #[serde(rename = "pv-composition-media-encrypted")]
    PvCompositionMediaEncrypted,
    #[serde(rename = "pv-composition-media-stored")]
    PvCompositionMediaStored,
    #[serde(rename = "pv-composition-minutes")]
    PvCompositionMinutes,
    #[serde(rename = "pv-recording-compositions")]
    PvRecordingCompositions,
    #[serde(rename = "pv-room-participants")]
    PvRoomParticipants,
    #[serde(rename = "pv-room-participants-au1")]
    PvRoomParticipantsAu1,
    #[serde(rename = "pv-room-participants-br1")]
    PvRoomParticipantsBr1,
    #[serde(rename = "pv-room-participants-ie1")]
    PvRoomParticipantsIe1,
    #[serde(rename = "pv-room-participants-jp1")]
    PvRoomParticipantsJp1,
    #[serde(rename = "pv-room-participants-sg1")]
    PvRoomParticipantsSg1,
    #[serde(rename = "pv-room-participants-us1")]
    PvRoomParticipantsUs1,
    #[serde(rename = "pv-room-participants-us2")]
    PvRoomParticipantsUs2,
    #[serde(rename = "pv-rooms")]
    PvRooms,
    #[serde(rename = "pv-sip-endpoint-registrations")]
    PvSipEndpointRegistrations,
    #[serde(rename = "recordings")]
    Recordings,
    #[serde(rename = "recordingstorage")]
    Recordingstorage,
    #[serde(rename = "rooms-group-bandwidth")]
    RoomsGroupBandwidth,
    #[serde(rename = "rooms-group-minutes")]
    RoomsGroupMinutes,
    #[serde(rename = "rooms-peer-to-peer-minutes")]
    RoomsPeerToPeerMinutes,
    #[serde(rename = "shortcodes")]
    Shortcodes,
    #[serde(rename = "shortcodes-customerowned")]
    ShortcodesCustomerowned,
    #[serde(rename = "shortcodes-mms-enablement")]
    ShortcodesMmsEnablement,
    #[serde(rename = "shortcodes-mps")]
    ShortcodesMps,
    #[serde(rename = "shortcodes-random")]
    ShortcodesRandom,
    #[serde(rename = "shortcodes-uk")]
    ShortcodesUk,
    #[serde(rename = "shortcodes-vanity")]
    ShortcodesVanity,
    #[serde(rename = "small-group-rooms")]
    SmallGroupRooms,
    #[serde(rename = "small-group-rooms-data-track")]
    SmallGroupRoomsDataTrack,
    #[serde(rename = "small-group-rooms-participant-minutes")]
    SmallGroupRoomsParticipantMinutes,
    #[serde(rename = "sms")]
    Sms,
    #[serde(rename = "sms-inbound")]
    SmsInbound,
    #[serde(rename = "sms-inbound-longcode")]
    SmsInboundLongcode,
    #[serde(rename = "sms-inbound-shortcode")]
    SmsInboundShortcode,
    #[serde(rename = "sms-messages-carrierfees")]
    SmsMessagesCarrierfees,
    #[serde(rename = "sms-messages-features")]
    SmsMessagesFeatures,
    #[serde(rename = "sms-messages-features-senderid")]
    SmsMessagesFeaturesSenderid,
    #[serde(rename = "sms-outbound")]
    SmsOutbound,
    #[serde(rename = "sms-outbound-content-inspection")]
    SmsOutboundContentInspection,
    #[serde(rename = "sms-outbound-longcode")]
    SmsOutboundLongcode,
    #[serde(rename = "sms-outbound-shortcode")]
    SmsOutboundShortcode,
    #[serde(rename = "speech-recognition")]
    SpeechRecognition,
    #[serde(rename = "studio-engagements")]
    StudioEngagements,
    #[serde(rename = "sync")]
    Sync,
    #[serde(rename = "sync-actions")]
    SyncActions,
    #[serde(rename = "sync-endpoint-hours")]
    SyncEndpointHours,
    #[serde(rename = "sync-endpoint-hours-above-daily-cap")]
    SyncEndpointHoursAboveDailyCap,
    #[serde(rename = "taskrouter-tasks")]
    TaskrouterTasks,
    #[serde(rename = "totalprice")]
    Totalprice,
    #[serde(rename = "transcriptions")]
    Transcriptions,
    #[serde(rename = "trunking-cps")]
    TrunkingCps,
    #[serde(rename = "trunking-emergency-calls")]
    TrunkingEmergencyCalls,
    #[serde(rename = "trunking-origination")]
    TrunkingOrigination,
    #[serde(rename = "trunking-origination-local")]
    TrunkingOriginationLocal,
    #[serde(rename = "trunking-origination-mobile")]
    TrunkingOriginationMobile,
    #[serde(rename = "trunking-origination-tollfree")]
    TrunkingOriginationTollfree,
    #[serde(rename = "trunking-recordings")]
    TrunkingRecordings,
    #[serde(rename = "trunking-secure")]
    TrunkingSecure,
    #[serde(rename = "trunking-termination")]
    TrunkingTermination,
    #[serde(rename = "turnmegabytes")]
    Turnmegabytes,
    #[serde(rename = "turnmegabytes-australia")]
    TurnmegabytesAustralia,
    #[serde(rename = "turnmegabytes-brasil")]
    TurnmegabytesBrasil,
    #[serde(rename = "turnmegabytes-germany")]
    TurnmegabytesGermany,
    #[serde(rename = "turnmegabytes-india")]
    TurnmegabytesIndia,
    #[serde(rename = "turnmegabytes-ireland")]
    TurnmegabytesIreland,
    #[serde(rename = "turnmegabytes-japan")]
    TurnmegabytesJapan,
    #[serde(rename = "turnmegabytes-singapore")]
    TurnmegabytesSingapore,
    #[serde(rename = "turnmegabytes-useast")]
    TurnmegabytesUseast,
    #[serde(rename = "turnmegabytes-uswest")]
    TurnmegabytesUswest,
    #[serde(rename = "twilio-interconnect")]
    TwilioInterconnect,
    #[serde(rename = "verify-push")]
    VerifyPush,
    #[serde(rename = "verify-totp")]
    VerifyTotp,
    #[serde(rename = "verify-whatsapp-conversations-business-initiated")]
    VerifyWhatsappConversationsBusinessInitiated,
    #[serde(rename = "video-recordings")]
    VideoRecordings,
    #[serde(rename = "virtual-agent")]
    VirtualAgent,
    #[serde(rename = "voice-insights")]
    VoiceInsights,
    #[serde(rename = "voice-insights-client-insights-on-demand-minute")]
    VoiceInsightsClientInsightsOnDemandMinute,
    #[serde(rename = "voice-insights-ptsn-insights-on-demand-minute")]
    VoiceInsightsPtsnInsightsOnDemandMinute,
    #[serde(rename = "voice-insights-sip-interface-insights-on-demand-minute")]
    VoiceInsightsSipInterfaceInsightsOnDemandMinute,
    #[serde(rename = "voice-insights-sip-trunking-insights-on-demand-minute")]
    VoiceInsightsSipTrunkingInsightsOnDemandMinute,
    #[serde(rename = "wireless")]
    Wireless,
    #[serde(rename = "wireless-orders")]
    WirelessOrders,
    #[serde(rename = "wireless-orders-artwork")]
    WirelessOrdersArtwork,
    #[serde(rename = "wireless-orders-bulk")]
    WirelessOrdersBulk,
    #[serde(rename = "wireless-orders-esim")]
    WirelessOrdersEsim,
    #[serde(rename = "wireless-orders-starter")]
    WirelessOrdersStarter,
    #[serde(rename = "wireless-usage")]
    WirelessUsage,
    #[serde(rename = "wireless-usage-commands")]
    WirelessUsageCommands,
    #[serde(rename = "wireless-usage-commands-africa")]
    WirelessUsageCommandsAfrica,
    #[serde(rename = "wireless-usage-commands-asia")]
    WirelessUsageCommandsAsia,
    #[serde(rename = "wireless-usage-commands-centralandsouthamerica")]
    WirelessUsageCommandsCentralandsouthamerica,
    #[serde(rename = "wireless-usage-commands-europe")]
    WirelessUsageCommandsEurope,
    #[serde(rename = "wireless-usage-commands-home")]
    WirelessUsageCommandsHome,
    #[serde(rename = "wireless-usage-commands-northamerica")]
    WirelessUsageCommandsNorthamerica,
    #[serde(rename = "wireless-usage-commands-oceania")]
    WirelessUsageCommandsOceania,
    #[serde(rename = "wireless-usage-commands-roaming")]
    WirelessUsageCommandsRoaming,
    #[serde(rename = "wireless-usage-data")]
    WirelessUsageData,
    #[serde(rename = "wireless-usage-data-africa")]
    WirelessUsageDataAfrica,
    #[serde(rename = "wireless-usage-data-asia")]
    WirelessUsageDataAsia,
    #[serde(rename = "wireless-usage-data-centralandsouthamerica")]
    WirelessUsageDataCentralandsouthamerica,
    #[serde(rename = "wireless-usage-data-custom-additionalmb")]
    WirelessUsageDataCustomAdditionalmb,
    #[serde(rename = "wireless-usage-data-custom-first5mb")]
    WirelessUsageDataCustomFirst5mb,
    #[serde(rename = "wireless-usage-data-domestic-roaming")]
    WirelessUsageDataDomesticRoaming,
    #[serde(rename = "wireless-usage-data-europe")]
    WirelessUsageDataEurope,
    #[serde(rename = "wireless-usage-data-individual-additionalgb")]
    WirelessUsageDataIndividualAdditionalgb,
    #[serde(rename = "wireless-usage-data-individual-firstgb")]
    WirelessUsageDataIndividualFirstgb,
    #[serde(rename = "wireless-usage-data-international-roaming-canada")]
    WirelessUsageDataInternationalRoamingCanada,
    #[serde(rename = "wireless-usage-data-international-roaming-india")]
    WirelessUsageDataInternationalRoamingIndia,
    #[serde(rename = "wireless-usage-data-international-roaming-mexico")]
    WirelessUsageDataInternationalRoamingMexico,
    #[serde(rename = "wireless-usage-data-northamerica")]
    WirelessUsageDataNorthamerica,
    #[serde(rename = "wireless-usage-data-oceania")]
    WirelessUsageDataOceania,
    #[serde(rename = "wireless-usage-data-pooled")]
    WirelessUsageDataPooled,
    #[serde(rename = "wireless-usage-data-pooled-downlink")]
    WirelessUsageDataPooledDownlink,
    #[serde(rename = "wireless-usage-data-pooled-uplink")]
    WirelessUsageDataPooledUplink,
    #[serde(rename = "wireless-usage-mrc")]
    WirelessUsageMrc,
    #[serde(rename = "wireless-usage-mrc-custom")]
    WirelessUsageMrcCustom,
    #[serde(rename = "wireless-usage-mrc-individual")]
    WirelessUsageMrcIndividual,
    #[serde(rename = "wireless-usage-mrc-pooled")]
    WirelessUsageMrcPooled,
    #[serde(rename = "wireless-usage-mrc-suspended")]
    WirelessUsageMrcSuspended,
    #[serde(rename = "wireless-usage-sms")]
    WirelessUsageSms,
    #[serde(rename = "wireless-usage-voice")]
    WirelessUsageVoice,

}

impl ToString for UsageRecordLastMonthEnumCategory {
    fn to_string(&self) -> String {
        match self {
            Self::A2pRegistrationFees => String::from("a2p-registration-fees"),
            Self::AgentConference => String::from("agent-conference"),
            Self::AmazonPolly => String::from("amazon-polly"),
            Self::AnsweringMachineDetection => String::from("answering-machine-detection"),
            Self::AuthyAuthentications => String::from("authy-authentications"),
            Self::AuthyCallsOutbound => String::from("authy-calls-outbound"),
            Self::AuthyMonthlyFees => String::from("authy-monthly-fees"),
            Self::AuthyPhoneIntelligence => String::from("authy-phone-intelligence"),
            Self::AuthyPhoneVerifications => String::from("authy-phone-verifications"),
            Self::AuthySmsOutbound => String::from("authy-sms-outbound"),
            Self::CallProgessEvents => String::from("call-progess-events"),
            Self::Calleridlookups => String::from("calleridlookups"),
            Self::Calls => String::from("calls"),
            Self::CallsClient => String::from("calls-client"),
            Self::CallsGlobalconference => String::from("calls-globalconference"),
            Self::CallsInbound => String::from("calls-inbound"),
            Self::CallsInboundLocal => String::from("calls-inbound-local"),
            Self::CallsInboundMobile => String::from("calls-inbound-mobile"),
            Self::CallsInboundTollfree => String::from("calls-inbound-tollfree"),
            Self::CallsOutbound => String::from("calls-outbound"),
            Self::CallsPayVerbTransactions => String::from("calls-pay-verb-transactions"),
            Self::CallsRecordings => String::from("calls-recordings"),
            Self::CallsSip => String::from("calls-sip"),
            Self::CallsSipInbound => String::from("calls-sip-inbound"),
            Self::CallsSipOutbound => String::from("calls-sip-outbound"),
            Self::CallsTransfers => String::from("calls-transfers"),
            Self::CarrierLookups => String::from("carrier-lookups"),
            Self::Conversations => String::from("conversations"),
            Self::ConversationsApiRequests => String::from("conversations-api-requests"),
            Self::ConversationsConversationEvents => String::from("conversations-conversation-events"),
            Self::ConversationsEndpointConnectivity => String::from("conversations-endpoint-connectivity"),
            Self::ConversationsEvents => String::from("conversations-events"),
            Self::ConversationsParticipantEvents => String::from("conversations-participant-events"),
            Self::ConversationsParticipants => String::from("conversations-participants"),
            Self::Cps => String::from("cps"),
            Self::FlexUsage => String::from("flex-usage"),
            Self::FraudLookups => String::from("fraud-lookups"),
            Self::GroupRooms => String::from("group-rooms"),
            Self::GroupRoomsDataTrack => String::from("group-rooms-data-track"),
            Self::GroupRoomsEncryptedMediaRecorded => String::from("group-rooms-encrypted-media-recorded"),
            Self::GroupRoomsMediaDownloaded => String::from("group-rooms-media-downloaded"),
            Self::GroupRoomsMediaRecorded => String::from("group-rooms-media-recorded"),
            Self::GroupRoomsMediaRouted => String::from("group-rooms-media-routed"),
            Self::GroupRoomsMediaStored => String::from("group-rooms-media-stored"),
            Self::GroupRoomsParticipantMinutes => String::from("group-rooms-participant-minutes"),
            Self::GroupRoomsRecordedMinutes => String::from("group-rooms-recorded-minutes"),
            Self::ImpV1Usage => String::from("imp-v1-usage"),
            Self::Lookups => String::from("lookups"),
            Self::Marketplace => String::from("marketplace"),
            Self::MarketplaceAlgorithmiaNamedEntityRecognition => String::from("marketplace-algorithmia-named-entity-recognition"),
            Self::MarketplaceCadenceTranscription => String::from("marketplace-cadence-transcription"),
            Self::MarketplaceCadenceTranslation => String::from("marketplace-cadence-translation"),
            Self::MarketplaceCapioSpeechToText => String::from("marketplace-capio-speech-to-text"),
            Self::MarketplaceConvrizaAbaba => String::from("marketplace-convriza-ababa"),
            Self::MarketplaceDeepgramPhraseDetector => String::from("marketplace-deepgram-phrase-detector"),
            Self::MarketplaceDigitalSegmentBusinessInfo => String::from("marketplace-digital-segment-business-info"),
            Self::MarketplaceFacebookOfflineConversions => String::from("marketplace-facebook-offline-conversions"),
            Self::MarketplaceGoogleSpeechToText => String::from("marketplace-google-speech-to-text"),
            Self::MarketplaceIbmWatsonMessageInsights => String::from("marketplace-ibm-watson-message-insights"),
            Self::MarketplaceIbmWatsonMessageSentiment => String::from("marketplace-ibm-watson-message-sentiment"),
            Self::MarketplaceIbmWatsonRecordingAnalysis => String::from("marketplace-ibm-watson-recording-analysis"),
            Self::MarketplaceIbmWatsonToneAnalyzer => String::from("marketplace-ibm-watson-tone-analyzer"),
            Self::MarketplaceIcehookSystemsScout => String::from("marketplace-icehook-systems-scout"),
            Self::MarketplaceInfogroupDataaxleBizinfo => String::from("marketplace-infogroup-dataaxle-bizinfo"),
            Self::MarketplaceKeenIoContactCenterAnalytics => String::from("marketplace-keen-io-contact-center-analytics"),
            Self::MarketplaceMarchexCleancall => String::from("marketplace-marchex-cleancall"),
            Self::MarketplaceMarchexSentimentAnalysisForSms => String::from("marketplace-marchex-sentiment-analysis-for-sms"),
            Self::MarketplaceMarketplaceNextcallerSocialId => String::from("marketplace-marketplace-nextcaller-social-id"),
            Self::MarketplaceMobileCommonsOptOutClassifier => String::from("marketplace-mobile-commons-opt-out-classifier"),
            Self::MarketplaceNexiwaveVoicemailToText => String::from("marketplace-nexiwave-voicemail-to-text"),
            Self::MarketplaceNextcallerAdvancedCallerIdentification => String::from("marketplace-nextcaller-advanced-caller-identification"),
            Self::MarketplaceNomoroboSpamScore => String::from("marketplace-nomorobo-spam-score"),
            Self::MarketplacePayfoneTcpaCompliance => String::from("marketplace-payfone-tcpa-compliance"),
            Self::MarketplaceRemeetingAutomaticSpeechRecognition => String::from("marketplace-remeeting-automatic-speech-recognition"),
            Self::MarketplaceTcpaDefenseSolutionsBlacklistFeed => String::from("marketplace-tcpa-defense-solutions-blacklist-feed"),
            Self::MarketplaceTeloOpencnam => String::from("marketplace-telo-opencnam"),
            Self::MarketplaceTruecnamTrueSpam => String::from("marketplace-truecnam-true-spam"),
            Self::MarketplaceTwilioCallerNameLookupUs => String::from("marketplace-twilio-caller-name-lookup-us"),
            Self::MarketplaceTwilioCarrierInformationLookup => String::from("marketplace-twilio-carrier-information-lookup"),
            Self::MarketplaceVoicebasePci => String::from("marketplace-voicebase-pci"),
            Self::MarketplaceVoicebaseTranscription => String::from("marketplace-voicebase-transcription"),
            Self::MarketplaceVoicebaseTranscriptionCustomVocabulary => String::from("marketplace-voicebase-transcription-custom-vocabulary"),
            Self::MarketplaceWhitepagesProCallerIdentification => String::from("marketplace-whitepages-pro-caller-identification"),
            Self::MarketplaceWhitepagesProPhoneIntelligence => String::from("marketplace-whitepages-pro-phone-intelligence"),
            Self::MarketplaceWhitepagesProPhoneReputation => String::from("marketplace-whitepages-pro-phone-reputation"),
            Self::MarketplaceWolfarmSpokenResults => String::from("marketplace-wolfarm-spoken-results"),
            Self::MarketplaceWolframShortAnswer => String::from("marketplace-wolfram-short-answer"),
            Self::MarketplaceYticaContactCenterReportingAnalytics => String::from("marketplace-ytica-contact-center-reporting-analytics"),
            Self::Mediastorage => String::from("mediastorage"),
            Self::Mms => String::from("mms"),
            Self::MmsInbound => String::from("mms-inbound"),
            Self::MmsInboundLongcode => String::from("mms-inbound-longcode"),
            Self::MmsInboundShortcode => String::from("mms-inbound-shortcode"),
            Self::MmsMessagesCarrierfees => String::from("mms-messages-carrierfees"),
            Self::MmsOutbound => String::from("mms-outbound"),
            Self::MmsOutboundLongcode => String::from("mms-outbound-longcode"),
            Self::MmsOutboundShortcode => String::from("mms-outbound-shortcode"),
            Self::MonitorReads => String::from("monitor-reads"),
            Self::MonitorStorage => String::from("monitor-storage"),
            Self::MonitorWrites => String::from("monitor-writes"),
            Self::Notify => String::from("notify"),
            Self::NotifyActionsAttempts => String::from("notify-actions-attempts"),
            Self::NotifyChannels => String::from("notify-channels"),
            Self::NumberFormatLookups => String::from("number-format-lookups"),
            Self::Pchat => String::from("pchat"),
            Self::PchatUsers => String::from("pchat-users"),
            Self::PeerToPeerRoomsParticipantMinutes => String::from("peer-to-peer-rooms-participant-minutes"),
            Self::Pfax => String::from("pfax"),
            Self::PfaxMinutes => String::from("pfax-minutes"),
            Self::PfaxMinutesInbound => String::from("pfax-minutes-inbound"),
            Self::PfaxMinutesOutbound => String::from("pfax-minutes-outbound"),
            Self::PfaxPages => String::from("pfax-pages"),
            Self::Phonenumbers => String::from("phonenumbers"),
            Self::PhonenumbersCps => String::from("phonenumbers-cps"),
            Self::PhonenumbersEmergency => String::from("phonenumbers-emergency"),
            Self::PhonenumbersLocal => String::from("phonenumbers-local"),
            Self::PhonenumbersMobile => String::from("phonenumbers-mobile"),
            Self::PhonenumbersSetups => String::from("phonenumbers-setups"),
            Self::PhonenumbersTollfree => String::from("phonenumbers-tollfree"),
            Self::Premiumsupport => String::from("premiumsupport"),
            Self::Proxy => String::from("proxy"),
            Self::ProxyActiveSessions => String::from("proxy-active-sessions"),
            Self::Pstnconnectivity => String::from("pstnconnectivity"),
            Self::Pv => String::from("pv"),
            Self::PvCompositionMediaDownloaded => String::from("pv-composition-media-downloaded"),
            Self::PvCompositionMediaEncrypted => String::from("pv-composition-media-encrypted"),
            Self::PvCompositionMediaStored => String::from("pv-composition-media-stored"),
            Self::PvCompositionMinutes => String::from("pv-composition-minutes"),
            Self::PvRecordingCompositions => String::from("pv-recording-compositions"),
            Self::PvRoomParticipants => String::from("pv-room-participants"),
            Self::PvRoomParticipantsAu1 => String::from("pv-room-participants-au1"),
            Self::PvRoomParticipantsBr1 => String::from("pv-room-participants-br1"),
            Self::PvRoomParticipantsIe1 => String::from("pv-room-participants-ie1"),
            Self::PvRoomParticipantsJp1 => String::from("pv-room-participants-jp1"),
            Self::PvRoomParticipantsSg1 => String::from("pv-room-participants-sg1"),
            Self::PvRoomParticipantsUs1 => String::from("pv-room-participants-us1"),
            Self::PvRoomParticipantsUs2 => String::from("pv-room-participants-us2"),
            Self::PvRooms => String::from("pv-rooms"),
            Self::PvSipEndpointRegistrations => String::from("pv-sip-endpoint-registrations"),
            Self::Recordings => String::from("recordings"),
            Self::Recordingstorage => String::from("recordingstorage"),
            Self::RoomsGroupBandwidth => String::from("rooms-group-bandwidth"),
            Self::RoomsGroupMinutes => String::from("rooms-group-minutes"),
            Self::RoomsPeerToPeerMinutes => String::from("rooms-peer-to-peer-minutes"),
            Self::Shortcodes => String::from("shortcodes"),
            Self::ShortcodesCustomerowned => String::from("shortcodes-customerowned"),
            Self::ShortcodesMmsEnablement => String::from("shortcodes-mms-enablement"),
            Self::ShortcodesMps => String::from("shortcodes-mps"),
            Self::ShortcodesRandom => String::from("shortcodes-random"),
            Self::ShortcodesUk => String::from("shortcodes-uk"),
            Self::ShortcodesVanity => String::from("shortcodes-vanity"),
            Self::SmallGroupRooms => String::from("small-group-rooms"),
            Self::SmallGroupRoomsDataTrack => String::from("small-group-rooms-data-track"),
            Self::SmallGroupRoomsParticipantMinutes => String::from("small-group-rooms-participant-minutes"),
            Self::Sms => String::from("sms"),
            Self::SmsInbound => String::from("sms-inbound"),
            Self::SmsInboundLongcode => String::from("sms-inbound-longcode"),
            Self::SmsInboundShortcode => String::from("sms-inbound-shortcode"),
            Self::SmsMessagesCarrierfees => String::from("sms-messages-carrierfees"),
            Self::SmsMessagesFeatures => String::from("sms-messages-features"),
            Self::SmsMessagesFeaturesSenderid => String::from("sms-messages-features-senderid"),
            Self::SmsOutbound => String::from("sms-outbound"),
            Self::SmsOutboundContentInspection => String::from("sms-outbound-content-inspection"),
            Self::SmsOutboundLongcode => String::from("sms-outbound-longcode"),
            Self::SmsOutboundShortcode => String::from("sms-outbound-shortcode"),
            Self::SpeechRecognition => String::from("speech-recognition"),
            Self::StudioEngagements => String::from("studio-engagements"),
            Self::Sync => String::from("sync"),
            Self::SyncActions => String::from("sync-actions"),
            Self::SyncEndpointHours => String::from("sync-endpoint-hours"),
            Self::SyncEndpointHoursAboveDailyCap => String::from("sync-endpoint-hours-above-daily-cap"),
            Self::TaskrouterTasks => String::from("taskrouter-tasks"),
            Self::Totalprice => String::from("totalprice"),
            Self::Transcriptions => String::from("transcriptions"),
            Self::TrunkingCps => String::from("trunking-cps"),
            Self::TrunkingEmergencyCalls => String::from("trunking-emergency-calls"),
            Self::TrunkingOrigination => String::from("trunking-origination"),
            Self::TrunkingOriginationLocal => String::from("trunking-origination-local"),
            Self::TrunkingOriginationMobile => String::from("trunking-origination-mobile"),
            Self::TrunkingOriginationTollfree => String::from("trunking-origination-tollfree"),
            Self::TrunkingRecordings => String::from("trunking-recordings"),
            Self::TrunkingSecure => String::from("trunking-secure"),
            Self::TrunkingTermination => String::from("trunking-termination"),
            Self::Turnmegabytes => String::from("turnmegabytes"),
            Self::TurnmegabytesAustralia => String::from("turnmegabytes-australia"),
            Self::TurnmegabytesBrasil => String::from("turnmegabytes-brasil"),
            Self::TurnmegabytesGermany => String::from("turnmegabytes-germany"),
            Self::TurnmegabytesIndia => String::from("turnmegabytes-india"),
            Self::TurnmegabytesIreland => String::from("turnmegabytes-ireland"),
            Self::TurnmegabytesJapan => String::from("turnmegabytes-japan"),
            Self::TurnmegabytesSingapore => String::from("turnmegabytes-singapore"),
            Self::TurnmegabytesUseast => String::from("turnmegabytes-useast"),
            Self::TurnmegabytesUswest => String::from("turnmegabytes-uswest"),
            Self::TwilioInterconnect => String::from("twilio-interconnect"),
            Self::VerifyPush => String::from("verify-push"),
            Self::VerifyTotp => String::from("verify-totp"),
            Self::VerifyWhatsappConversationsBusinessInitiated => String::from("verify-whatsapp-conversations-business-initiated"),
            Self::VideoRecordings => String::from("video-recordings"),
            Self::VirtualAgent => String::from("virtual-agent"),
            Self::VoiceInsights => String::from("voice-insights"),
            Self::VoiceInsightsClientInsightsOnDemandMinute => String::from("voice-insights-client-insights-on-demand-minute"),
            Self::VoiceInsightsPtsnInsightsOnDemandMinute => String::from("voice-insights-ptsn-insights-on-demand-minute"),
            Self::VoiceInsightsSipInterfaceInsightsOnDemandMinute => String::from("voice-insights-sip-interface-insights-on-demand-minute"),
            Self::VoiceInsightsSipTrunkingInsightsOnDemandMinute => String::from("voice-insights-sip-trunking-insights-on-demand-minute"),
            Self::Wireless => String::from("wireless"),
            Self::WirelessOrders => String::from("wireless-orders"),
            Self::WirelessOrdersArtwork => String::from("wireless-orders-artwork"),
            Self::WirelessOrdersBulk => String::from("wireless-orders-bulk"),
            Self::WirelessOrdersEsim => String::from("wireless-orders-esim"),
            Self::WirelessOrdersStarter => String::from("wireless-orders-starter"),
            Self::WirelessUsage => String::from("wireless-usage"),
            Self::WirelessUsageCommands => String::from("wireless-usage-commands"),
            Self::WirelessUsageCommandsAfrica => String::from("wireless-usage-commands-africa"),
            Self::WirelessUsageCommandsAsia => String::from("wireless-usage-commands-asia"),
            Self::WirelessUsageCommandsCentralandsouthamerica => String::from("wireless-usage-commands-centralandsouthamerica"),
            Self::WirelessUsageCommandsEurope => String::from("wireless-usage-commands-europe"),
            Self::WirelessUsageCommandsHome => String::from("wireless-usage-commands-home"),
            Self::WirelessUsageCommandsNorthamerica => String::from("wireless-usage-commands-northamerica"),
            Self::WirelessUsageCommandsOceania => String::from("wireless-usage-commands-oceania"),
            Self::WirelessUsageCommandsRoaming => String::from("wireless-usage-commands-roaming"),
            Self::WirelessUsageData => String::from("wireless-usage-data"),
            Self::WirelessUsageDataAfrica => String::from("wireless-usage-data-africa"),
            Self::WirelessUsageDataAsia => String::from("wireless-usage-data-asia"),
            Self::WirelessUsageDataCentralandsouthamerica => String::from("wireless-usage-data-centralandsouthamerica"),
            Self::WirelessUsageDataCustomAdditionalmb => String::from("wireless-usage-data-custom-additionalmb"),
            Self::WirelessUsageDataCustomFirst5mb => String::from("wireless-usage-data-custom-first5mb"),
            Self::WirelessUsageDataDomesticRoaming => String::from("wireless-usage-data-domestic-roaming"),
            Self::WirelessUsageDataEurope => String::from("wireless-usage-data-europe"),
            Self::WirelessUsageDataIndividualAdditionalgb => String::from("wireless-usage-data-individual-additionalgb"),
            Self::WirelessUsageDataIndividualFirstgb => String::from("wireless-usage-data-individual-firstgb"),
            Self::WirelessUsageDataInternationalRoamingCanada => String::from("wireless-usage-data-international-roaming-canada"),
            Self::WirelessUsageDataInternationalRoamingIndia => String::from("wireless-usage-data-international-roaming-india"),
            Self::WirelessUsageDataInternationalRoamingMexico => String::from("wireless-usage-data-international-roaming-mexico"),
            Self::WirelessUsageDataNorthamerica => String::from("wireless-usage-data-northamerica"),
            Self::WirelessUsageDataOceania => String::from("wireless-usage-data-oceania"),
            Self::WirelessUsageDataPooled => String::from("wireless-usage-data-pooled"),
            Self::WirelessUsageDataPooledDownlink => String::from("wireless-usage-data-pooled-downlink"),
            Self::WirelessUsageDataPooledUplink => String::from("wireless-usage-data-pooled-uplink"),
            Self::WirelessUsageMrc => String::from("wireless-usage-mrc"),
            Self::WirelessUsageMrcCustom => String::from("wireless-usage-mrc-custom"),
            Self::WirelessUsageMrcIndividual => String::from("wireless-usage-mrc-individual"),
            Self::WirelessUsageMrcPooled => String::from("wireless-usage-mrc-pooled"),
            Self::WirelessUsageMrcSuspended => String::from("wireless-usage-mrc-suspended"),
            Self::WirelessUsageSms => String::from("wireless-usage-sms"),
            Self::WirelessUsageVoice => String::from("wireless-usage-voice"),
        }
    }
}

impl Default for UsageRecordLastMonthEnumCategory {
    fn default() -> UsageRecordLastMonthEnumCategory {
        Self::A2pRegistrationFees
    }
}




