// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '<api_key>',
    appId: '1:<project_number>:web:322a8846fc2db3f277d6c8',
    messagingSenderId: '<project_number>',
    projectId: '<project_id>',
    authDomain: '<project_id>.firebaseapp.com',
    storageBucket: '<project_id>.appspot.com',
    measurementId: 'G-GVGTGPQ79B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '<api_key>',
    appId: '1:<project_number>:android:e9210cd7443dfb7c77d6c8',
    messagingSenderId: '<project_number>',
    projectId: '<project_id>',
    storageBucket: '<project_id>.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '<api_key>',
    appId: '1:<project_number>:ios:94253b1e1aef598a77d6c8',
    messagingSenderId: '<project_number>',
    projectId: '<project_id>',
    storageBucket: '<project_id>.appspot.com',
    iosClientId: '<project_number>-ninugevc81676tra76fbllfl0o29viod.apps.googleusercontent.com',
    iosBundleId: 'io.qcodelabs.proche.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: '<api_key>',
    appId: '1:<project_number>:ios:e825fc5ab9f73baf77d6c8',
    messagingSenderId: '<project_number>',
    projectId: '<project_id>',
    storageBucket: '<project_id>.appspot.com',
    iosClientId: '<project_number>-7e0dmtvm7g81a25v8ng8316kkjg0rh7i.apps.googleusercontent.com',
    iosBundleId: 'io.qcodelabs.nearme.mobile',
  );
}
