name: CI for Mobile App
on:
  pull_request:
    branches:
      - dev

jobs:
  flutter_test:
    name: Run a Flutter test & analyze
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/cache@v2
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-
      - name: Get dependencies
        run: flutter pub get
        working-directory: mobile
      - name: Analyze
        run: flutter analyze
        working-directory: mobile
      - name: Run tests
        run: flutter test
        working-directory: mobile
